<<<<<<< HEAD
services:
  - type: web
    name: t5-beta
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    autoDeploy: true
=======
services:
  - type: web
    name: t5-beta
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    autoDeploy: true
>>>>>>> 35705e445eb7275a47d1333d5659d117538942ed
